import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  docusSidebar: [
    {type: 'autogenerated', dirName: 'tools/docusaurus'}
  ],
  gitSidebar: [
    {type: 'autogenerated', dirName: 'tools/git'}
  ],
  contactSidebar: [
    {type: 'autogenerated', dirName: 'contact'}
  ],
  joinusSidebar: [
    {type: 'autogenerated', dirName: 'join-us'}
  ],
  rosSidebar: [
    {type: 'autogenerated', dirName: 'ros'}
  ],
};

export default sidebars;
